/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class JuceDemoPluginAudioProcessorEditor  : public AudioProcessorEditor,
											public Button::Listener,
											public Slider::Listener,
                                            private MultiTimer
{
public:
    JuceDemoPluginAudioProcessorEditor (JuceDemoPluginAudioProcessor&);
    ~JuceDemoPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void timerCallback (int ID) override;

private:

    MidiKeyboardComponent midiKeyboard;
    Label timecodeDisplayLabel, gainLabel, delayLabel;

    ScopedPointer<Slider> gainSlider, delaySlider;
    ScopedPointer<AudioProcessorValueTreeState::SliderAttachment> gainSliderAttachment, delaySliderAttachment;

	ScopedPointer<TextButton> undoButton, redoButton;	

    //==============================================================================
    JuceDemoPluginAudioProcessor& getProcessor() const
    {
        return static_cast<JuceDemoPluginAudioProcessor&> (processor);
    }

	void updateTimecodeDisplay (AudioPlayHead::CurrentPositionInfo);

	void sliderDragEnded (Slider* slider) override;
	void sliderValueChanged (Slider* slider) override; // not being used, but pure virtual function requires implementation
	void buttonClicked (Button* button) override;
	void setUndoRedoButtons();    
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
